export class MsnPurposeService {

    PURPOSE = [
        ['AE', 'AEROMEDICAL_EVACUATION'],
        ['AFRC', 'AFRC'],
        ['AIREV', 'AEROMEDICAL_EVACUATION', 'ANG'],
        ['AR', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['AREXER', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['CHANL', 'CHANNEL'],
        ['CNTNG', 'TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['CORNET', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['EXER', 'TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['GRDLFT', 'ANG'],
        ['JAATT', 'JOINT_AIRBORNE_AIR_TRANSPORT_TRANING'],
        ['JCSEXER', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['MISC', 'MISC'],
        ['OPLAN', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['OPORD', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['SAAM', 'SPECIAL_ASSIGNMENT_AIRLIFT_MISSION'],
        ['SAM', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['SUPT', 'OPERATIONAL_SUPPORT_AIRLIFT', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG', 'AFSOC'],
        ['TRNG', 'LOCAL_TRAINING', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG']
    ];

    type = {
        CHANNEL: ['CHANL'],
        SPECIAL_ASSIGNMENT_AIRLIFT_MISSION: ['SAAM'],
        JOINT_AIRBORNE_AIR_TRANSPORT_TRANING: ['JAATT'],
        AEROMEDICAL_EVACUATION: ['AIREV', 'AE'],
        CONTINGENCY_OPLAN_EXERCISE: ['CNTNG', 'OPLAN', 'OPORD', 'JCSEXER', 'EXER', 'AREXER'],
        OPERATIONAL_SUPPORT_AIRLIFT: ['SUPT'],
        EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION: ['SAM', 'SUPT', 'TRNG', 'CORNET', 'AR'],
        TANKER_AIR_REFUELING: ['CNTNG', 'EXER'],
        ANG: ['GRDLFT', 'SUPT', 'AIREV', 'TRNG'],
        AFSOC: ['SUPT'],
        LOCAL_TRAINING: ['TRNG'],
        AFRC: ['AFRC'],
        MISC: ['MISC']
    };


    // Donno wha to do with this, put it in a function, but it's worthless to me now - too scared to delete.
 PURPOSE_EXPAND = {
        AE : ['AEROMEDICAL_EVACUATION'],
        AFRC : ['AFRC'],
        AIREV : ['AEROMEDICAL_EVACUATION', 'ANG'],
        AR : ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        AREXER : ['CONTINGENCY_OPLAN_EXCERCISE'],
        CHANL : ['CHANNEL'],
        CNTNG : ['TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        CORNET : ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        EXER : ['TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        GRDLFT : ['ANG'],
        JAATT : ['JOINT_AIRBORNE_AIR_TRANSPORT_TRANING'],
        JCSEXER : ['CONTINGENCY_OPLAN_EXERCISE'],
        MISC : ['MISC'],
        OPLAN : ['CONTINGENCY_OPLAN_EXERCISE'],
        OPORD : ['CONTINGENCY_OPLAN_EXERCISE'],
        SAAM : ['SPECIAL_ASSIGNMENT_AIRLIFT_MISSION'],
        SAM : ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        SUPT : ['OPERATIONAL_SUPPORT_AIRLIFT', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG', 'AFSOC'],
        TRNG : ['LOCAL_TRAINING', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG'],
    };


DECODE_MAP = {
        CHANNEL: 'chanelDecode',
        SPECIAL_ASSIGNMENT_AIRLIFT_MISSION: 'saamDecode',
        JOINT_AIRBORNE_AIR_TRANSPORT_TRANING: 'jaattDecode',
        AEROMEDICAL_EVACUATION: ['airevOCONUSDecode', 'airevCONUSDecode'],
        CONTINGENCY_OPLAN_EXERCISE: 'coeDecode',
        OPERATIONAL_SUPPORT_AIRLIFT: 'osaDecode',
        EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION: 'samDecode',
        TANKER_AIR_REFUELING: 'aarDecode',
        LOCAL_TRAINING: 'nodecodenow',
}

}


// DECODE_MAP = {
//         CHANNEL: ['CHANL'],
//         SPECIAL_ASSIGNMENT_AIRLIFT_MISSION: ['SAAM'],
//         JOINT_AIRBORNE_AIR_TRANSPORT_TRANING: ['JAATT'],
//         AEROMEDICAL_EVACUATION: ['AIREV', 'AE'],
//         CONTINGENCY_OPLAN_EXERCISE: ['CNTNG', 'OPLAN', 'OPORD', 'JCSEXER', 'EXER', 'AREXER'],
//         OPERATIONAL_SUPPORT_AIRLIFT: ['SUPT'],
//         EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION: ['SAM', 'SUPT', 'TRNG', 'CORNET', 'AR'],
//         TANKER_AIR_REFUELING: ['CNTNG', 'EXER'],
//         ANG: ['GRDLFT', 'SUPT', 'AIREV', 'TRNG'],
//         AFSOC: ['SUPT'],
//         LOCAL_TRAINING: ['TRNG'],
//         AFRC: ['AFRC'],
//         MISC: ['MISC']
// }
