export class Purpose {

    PURPOSE = [
        ['AE', 'AEROMEDICAL_EVACUATION'],
        ['AFRC', 'AFRC'],
        ['AIREV', 'AEROMEDICAL_EVACUATION', 'ANG'],
        ['AR', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['AREXER', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['CHANL', 'CHANNEL'],
        ['CNTNG', 'TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['CORNET', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['EXER', 'TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'],
        ['GRDLFT', 'ANG'],
        ['JAATT', 'JOINT_AIRBORNE_AIR_TRANSPORT_TRANING'],
        ['JCSEXER', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['MISC', 'MISC'],
        ['OPLAN', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['OPORD', 'CONTINGENCY_OPLAN_EXERCISE'],
        ['SAAM', 'SPECIAL_ASSIGNMENT_AIRLIFT_MISSION'],
        ['SAM', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'],
        ['SUPT', 'OPERATIONAL_SUPPORT_AIRLIFT', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG', 'AFSOC'],
        ['TRNG', 'LOCAL_TRAINING', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG']
    ];

    type = {
        CHANNEL: ['CHANL'],
        SPECIAL_ASSIGNMENT_AIRLIFT_MISSION: ['SAAM'],
        JOINT_AIRBORNE_AIR_TRANSPORT_TRANING: ['JAATT'],
        AEROMEDICAL_EVACUATION: ['AIREV', 'AE'],
        CONTINGENCY_OPLAN_EXERCISE: ['CNTNG', 'OPLAN', 'OPORD', 'JCSEXER', 'EXER', 'AREXER'],
        OPERATIONAL_SUPPORT_AIRLIFT: ['SUPT'],
        EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION: ['SAM', 'SUPT', 'TRNG', 'CORNET', 'AR'],
        TANKER_AIR_REFUELING: ['CNTNG', 'EXER'],
        ANG: ['GRDLFT', 'SUPT', 'AIREV', 'TRNG'],
        AFSOC: ['SUPT'],
        LOCAL_TRAINING: ['TRNG'],
        AFRC: ['AFRC'],
        MISC: ['MISC']
    };


    // Donno wha to do with this, put it in a function, but it's worthless to me now - too scared to delete.
    function() {
        const AE = ['AEROMEDICAL_EVACUATION'];
        const AFRC = ['AFRC'];
        const AIREV = ['AEROMEDICAL_EVACUATION', 'ANG'];
        const AR = ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'];
        const AREXER = ['CONTINGENCY_OPLAN_EXCERCISE'];
        const CHANL = ['CHANNEL'];
        const CNTNG = ['TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'];
        const CORNET = ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'];
        const EXER = ['TANKER_AIR_REFUELING', 'CONTINGENCY_OPLAN_EXCERCISE'];
        const GRDLFT = ['ANG'];
        const JAATT = ['JOINT_AIRBORNE_AIR_TRANSPORT_TRANING'];
        const JCSEXER = ['CONTINGENCY_OPLAN_EXERCISE'];
        const MISC = ['MISC'];
        const OPLAN = ['CONTINGENCY_OPLAN_EXERCISE'];
        const OPORD = ['CONTINGENCY_OPLAN_EXERCISE'];
        const SAAM = ['SPECIAL_ASSIGNMENT_AIRLIFT_MISSION'];
        const SAM = ['EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION'];
        const SUPT = ['OPERATIONAL_SUPPORT_AIRLIFT', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG', 'AFSOC'];
        const TRNG = ['LOCAL_TRAINING', 'EXECUTIVE_AIRCRAFT_SPECIAL_AIR_MISSION', 'ANG'];
    }
}
